# Generated by Django 5.1.6 on 2025-02-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flightApp", "0002_alter_reservation_flight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passenger",
            name="email",
            field=models.CharField(max_length=25),
        ),
    ]
